## Solving Systems of Linear Equations

**System of Linear Equations**

$2x_1 + 3x_2 - x_3 = 1$

$4x_1 + x_2 + 2x_3 = -2$

$-x_1 + 2x_2 + 3x_3 = 3$

**To solve a linear system**

$A \cdot X = b \implies X = A^{-1} \cdot b,$ $\quad X = [x_1, x_2, x_3]$

In [29]:
import numpy as np

In [30]:
# The coefficient matrix A

A = np.array([[2, 3, -1],
              [4, 1, 2],
              [-1, 2, 3]])

In [31]:
# The constant vector
b = np.array([1, -2, 3])

In [32]:
# We'll use the inverse function of linear Algebra module in Numpy library.

A_inverse = np.linalg.inv(A)
A_inverse

array([[ 0.01886792,  0.20754717, -0.13207547],
       [ 0.26415094, -0.09433962,  0.1509434 ],
       [-0.16981132,  0.13207547,  0.18867925]])

In [33]:
# We'll use the matrix multiplication function in Numpy library.

X = np.matmul(A_inverse,b)
X

array([-0.79245283,  0.90566038,  0.13207547])

In [34]:
print("The solution of Linear Equations:")
print("x_1 = ",X[0])
print("x_2 = ",X[1])
print("x_3 = ",X[2])

The solution of Linear Equations:
x_1 =  -0.7924528301886793
x_2 =  0.9056603773584906
x_3 =  0.13207547169811323


In [35]:
def solution_linear_equations(coefficients, constants):
    try:
        A = np.array(coefficients)
        b = np.array(constants)
        A_inverse = np.linalg.inv(A)
        X = np.matmul(A_inverse,b)
        return X
# if A matrix does not have an inverse matrix, then
    except np.linalg.LinAlgError:
        return "There is no solution of this linear system"

In [36]:
solution_linear_equations(A, b)

array([-0.79245283,  0.90566038,  0.13207547])

In [37]:
# Linear Algebra module has an function for the solution:

x = np.linalg.solve(A,b)
x

array([-0.79245283,  0.90566038,  0.13207547])

In [38]:
solution_linear_equations(A, b) == x

array([ True,  True, False])